# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwshUKEBusYNsPWc0sefxqU89wdbrqNh
"""

import pandas as pd


# Step 1 : Load the CSV file into a DataFrame
df = pd.read_csv("/content/Data.csv")

# Step 3: Perform operations

# Filtering data where 'Y-Kappa' > 25
filtered_df = df[df['Y-Kappa'] > 25]

# Handling missing values
df_filled = df.fillna(0)            # Fill NaN with 0
df_ffill = df.fillna(method='ffill') # Forward fill
df_bfill = df.fillna(method='bfill') # Backward fill
df_dropped = df.dropna()             # Drop rows with any NaN values
df_dropped_cols = df.dropna(axis=1)  # Drop columns with any NaN values

# Calculating summary statistics
summary_stats = df.describe()        # Summary statistics
mean_y_kappa = df['Y-Kappa'].mean()  # Mean of 'Y-Kappa'
median_y_kappa = df['Y-Kappa'].median() # Median of 'Y-Kappa'
std_dev_y_kappa = df['Y-Kappa'].std()  # Standard deviation of 'Y-Kappa'

# Display results
print("Filtered DataFrame:\n", filtered_df)
print("DataFrame with NaN filled with 0:\n", df_filled)
print("DataFrame with forward fill:\n", df_ffill)
print("DataFrame with backward fill:\n", df_bfill)
print("DataFrame with rows with any NaN dropped:\n", df_dropped)
print("DataFrame with columns with any NaN dropped:\n", df_dropped_cols)
print("Summary statistics:\n", summary_stats)
print("Mean of 'Y-Kappa':", mean_y_kappa)
print("Median of 'Y-Kappa':", median_y_kappa)
print("Standard deviation of 'Y-Kappa':", std_dev_y_kappa)

